CREATE TABLE [dbo].[Option]
(
	[OptionId] INT NOT NULL PRIMARY KEY, 
    [Option1] NVARCHAR(200) NOT NULL, 
    [Option2] NVARCHAR(200) NOT NULL, 
    [Option3] NVARCHAR(200) NOT NULL, 
    [Option4] NVARCHAR(200) NOT NULL
)
